/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author inmac
 */
public class NuevaPropuesta extends javax.swing.JFrame {

    /**
     * Creates new form NuevaPropuesta
     */
    public NuevaPropuesta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelGEONORTE = new javax.swing.JLabel();
        jLabelNuevaPropuesta = new javax.swing.JLabel();
        jLabelCodProyecto = new javax.swing.JLabel();
        jTextFieldCodProyecto = new javax.swing.JTextField();
        jLabelCoste = new javax.swing.JLabel();
        jTextFieldCoste = new javax.swing.JTextField();
        jLabelCoordenadas = new javax.swing.JLabel();
        jTextFieldCoordenadas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelCertificacionesyLicencias = new javax.swing.JLabel();
        jTextFieldCertificaciones = new javax.swing.JTextField();
        jLabelInvestigacionPrevia = new javax.swing.JLabel();
        jLabelFechaInicio = new javax.swing.JLabel();
        jTextFieldFechaInicio = new javax.swing.JTextField();
        jLabelFechaFin = new javax.swing.JLabel();
        jTextFieldFechaFin = new javax.swing.JTextField();
        jComboBoxInvestigacion = new javax.swing.JComboBox<>();
        jLabelMargenContingencia = new javax.swing.JLabel();
        jTextFieldMargenContingencia = new javax.swing.JTextField();
        jLabelPorcentajeSaturacion = new javax.swing.JLabel();
        jTextFieldPorcentajeSaturacion = new javax.swing.JTextField();
        jLabelTiempoGarantia = new javax.swing.JLabel();
        jTextFieldTiempoGarantia = new javax.swing.JTextField();
        jLabelTipoRoca = new javax.swing.JLabel();
        jTextFieldTipoRoca = new javax.swing.JTextField();
        jLabelZonaTectonica = new javax.swing.JLabel();
        jTextFieldTipoZonaTectonica = new javax.swing.JTextField();
        jLabelZonasSingulares = new javax.swing.JLabel();
        jTextFieldZonasSingulares = new javax.swing.JTextField();
        jLabelDiscontinuidades = new javax.swing.JLabel();
        jComboBoxDiscontinuidades = new javax.swing.JComboBox<>();
        jLabelDiseñoEstabilizacion = new javax.swing.JLabel();
        jComboBoxEstabilizacion = new javax.swing.JComboBox<>();
        jButtonGuardar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelGEONORTE.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelGEONORTE.setText("GEONORTE S.A.");
        jLabelGEONORTE.setAlignmentX(1.0F);
        jLabelGEONORTE.setAlignmentY(0.7F);

        jLabelNuevaPropuesta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelNuevaPropuesta.setText("Nueva propuesta");

        jLabelCodProyecto.setText("Código proyecto");

        jLabelCoste.setText("Coste");

        jTextFieldCoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCosteActionPerformed(evt);
            }
        });

        jLabelCoordenadas.setText("Coordenadas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Datos técnicos");

        jLabelCertificacionesyLicencias.setText("Certificaciones y licencias");

        jLabelInvestigacionPrevia.setText("Investigación previa");

        jLabelFechaInicio.setText("Fecha de inicio");

        jLabelFechaFin.setText("Fecha de fin");

        jComboBoxInvestigacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Sí", "No" }));

        jLabelMargenContingencia.setText("Margen de contingencia");

        jLabelPorcentajeSaturacion.setText("Porcentaje de saturación");

        jLabelTiempoGarantia.setText("Tiempo de garantía");

        jLabelTipoRoca.setText("Tipo de roca");

        jLabelZonaTectonica.setText("Tipo de zona tectónica");

        jLabelZonasSingulares.setText("Zonas singulares");

        jLabelDiscontinuidades.setText("Discontinuidades");

        jComboBoxDiscontinuidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja una opción", "Fallamiento", "Disclasas", "Foliaciones", "Estratificación" }));

        jLabelDiseñoEstabilizacion.setText("Diseño de estabilización");

        jComboBoxEstabilizacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja una opción", "Activo", "Pasivo", "Mixto" }));

        jButtonGuardar.setText("Guardar");

        jButtonSalir.setText("Salir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabelGEONORTE, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNuevaPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelCodProyecto)
                                    .addComponent(jTextFieldCodProyecto)
                                    .addComponent(jLabelCoste, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCoste)
                                    .addComponent(jLabelCoordenadas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCoordenadas, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                                .addGap(97, 97, 97)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldFechaInicio)
                                    .addComponent(jLabelFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldFechaFin)
                                    .addComponent(jLabelMargenContingencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldMargenContingencia)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCertificacionesyLicencias, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCertificaciones))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelZonasSingulares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelTiempoGarantia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelPorcentajeSaturacion, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(jLabelInvestigacionPrevia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelTipoRoca, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelZonaTectonica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelDiscontinuidades, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDiseñoEstabilizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxInvestigacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldPorcentajeSaturacion)
                                    .addComponent(jTextFieldTiempoGarantia)
                                    .addComponent(jTextFieldTipoRoca)
                                    .addComponent(jTextFieldTipoZonaTectonica)
                                    .addComponent(jTextFieldZonasSingulares)
                                    .addComponent(jComboBoxDiscontinuidades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxEstabilizacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(311, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonGuardar)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalir)
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelGEONORTE, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNuevaPropuesta)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodProyecto)
                    .addComponent(jLabelFechaInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCoste)
                    .addComponent(jLabelFechaFin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCoordenadas)
                    .addComponent(jLabelMargenContingencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCoordenadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMargenContingencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCertificacionesyLicencias)
                    .addComponent(jTextFieldCertificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInvestigacionPrevia)
                    .addComponent(jComboBoxInvestigacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPorcentajeSaturacion)
                    .addComponent(jTextFieldPorcentajeSaturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTiempoGarantia)
                    .addComponent(jTextFieldTiempoGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTipoRoca)
                    .addComponent(jTextFieldTipoRoca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelZonaTectonica)
                    .addComponent(jTextFieldTipoZonaTectonica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelZonasSingulares)
                    .addComponent(jTextFieldZonasSingulares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDiscontinuidades)
                    .addComponent(jComboBoxDiscontinuidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDiseñoEstabilizacion)
                    .addComponent(jComboBoxEstabilizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonSalir))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCosteActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCosteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
        UIManager.setLookAndFeel(new FlatIntelliJLaf());
    } catch (UnsupportedLookAndFeelException e) {
        System.out.println("Error al ejecutar FlatLaf");
    }

    java.awt.EventQueue.invokeLater(() -> {
        new NuevaPropuesta().setVisible(true);
    });
}

    public JButton getjButtonGuardar() {
        return jButtonGuardar;
    }

    public JButton getjButtonSalir() {
        return jButtonSalir;
    }

    public JComboBox<String> getjComboBoxDiscontinuidades() {
        return jComboBoxDiscontinuidades;
    }

    public JComboBox<String> getjComboBoxEstabilizacion() {
        return jComboBoxEstabilizacion;
    }

    public JComboBox<String> getjComboBoxInvestigacion() {
        return jComboBoxInvestigacion;
    }

    public JTextField getjTextFieldCertificaciones() {
        return jTextFieldCertificaciones;
    }

    public JTextField getjTextFieldCodProyecto() {
        return jTextFieldCodProyecto;
    }

    public JTextField getjTextFieldCoordenadas() {
        return jTextFieldCoordenadas;
    }

    public JTextField getjTextFieldCoste() {
        return jTextFieldCoste;
    }

    public JTextField getjTextFieldFechaFin() {
        return jTextFieldFechaFin;
    }

    public JTextField getjTextFieldFechaInicio() {
        return jTextFieldFechaInicio;
    }

    public JTextField getjTextFieldMargenContingencia() {
        return jTextFieldMargenContingencia;
    }

    public JTextField getjTextFieldPorcentajeSaturacion() {
        return jTextFieldPorcentajeSaturacion;
    }

    public JTextField getjTextFieldTiempoGarantia() {
        return jTextFieldTiempoGarantia;
    }

    public JTextField getjTextFieldTipoRoca() {
        return jTextFieldTipoRoca;
    }

    public JTextField getjTextFieldTipoZonaTectonica() {
        return jTextFieldTipoZonaTectonica;
    }
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxDiscontinuidades;
    private javax.swing.JComboBox<String> jComboBoxEstabilizacion;
    private javax.swing.JComboBox<String> jComboBoxInvestigacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCertificacionesyLicencias;
    private javax.swing.JLabel jLabelCodProyecto;
    private javax.swing.JLabel jLabelCoordenadas;
    private javax.swing.JLabel jLabelCoste;
    private javax.swing.JLabel jLabelDiscontinuidades;
    private javax.swing.JLabel jLabelDiseñoEstabilizacion;
    private javax.swing.JLabel jLabelFechaFin;
    private javax.swing.JLabel jLabelFechaInicio;
    private javax.swing.JLabel jLabelGEONORTE;
    private javax.swing.JLabel jLabelInvestigacionPrevia;
    private javax.swing.JLabel jLabelMargenContingencia;
    private javax.swing.JLabel jLabelNuevaPropuesta;
    private javax.swing.JLabel jLabelPorcentajeSaturacion;
    private javax.swing.JLabel jLabelTiempoGarantia;
    private javax.swing.JLabel jLabelTipoRoca;
    private javax.swing.JLabel jLabelZonaTectonica;
    private javax.swing.JLabel jLabelZonasSingulares;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldCertificaciones;
    private javax.swing.JTextField jTextFieldCodProyecto;
    private javax.swing.JTextField jTextFieldCoordenadas;
    private javax.swing.JTextField jTextFieldCoste;
    private javax.swing.JTextField jTextFieldFechaFin;
    private javax.swing.JTextField jTextFieldFechaInicio;
    private javax.swing.JTextField jTextFieldMargenContingencia;
    private javax.swing.JTextField jTextFieldPorcentajeSaturacion;
    private javax.swing.JTextField jTextFieldTiempoGarantia;
    private javax.swing.JTextField jTextFieldTipoRoca;
    private javax.swing.JTextField jTextFieldTipoZonaTectonica;
    private javax.swing.JTextField jTextFieldZonasSingulares;
    // End of variables declaration//GEN-END:variables
}
