/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.UIManager;

/**
 *
 * @author inmac
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form app
     */
    public Principal() {
        initComponents();
         setDefaultCloseOperation(Principal.EXIT_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelGeonorte = new javax.swing.JLabel();
        jButtonNuevoCliente = new javax.swing.JButton();
        jButtonNuevaPropuesta = new javax.swing.JButton();
        jButtonNuevoProyecto = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonNuevoContrato = new javax.swing.JButton();
        jButtonBuscarTrabajador = new javax.swing.JButton();
        jButtonNuevoTrabajador = new javax.swing.JButton();
        jLabelicono = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelGeonorte.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelGeonorte.setText("GEONORTE S.A.");

        jButtonNuevoCliente.setText("Nuevo cliente");

        jButtonNuevaPropuesta.setText("Nueva propuesta");

        jButtonNuevoProyecto.setText("Nuevo Proyecto");

        jButtonBuscar.setText("Buscar");

        jButtonNuevoContrato.setText("Nuevo contrato");

        jButtonBuscarTrabajador.setText("Buscar trabajador/a");

        jButtonNuevoTrabajador.setText("Nuevo trabajador/a");

        jLabelicono.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscarTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNuevoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNuevaPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNuevoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNuevoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelGeonorte, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabelicono, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGeonorte)
                    .addComponent(jLabelicono))
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonBuscarTrabajador)
                    .addComponent(jButtonNuevoTrabajador))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevoCliente)
                    .addComponent(jButtonNuevaPropuesta)
                    .addComponent(jButtonNuevoProyecto)
                    .addComponent(jButtonNuevoContrato))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
        UIManager.setLookAndFeel(new FlatIntelliJLaf());
    } catch (Exception e) {
        System.err.println("Error al cargar FlatLaf");
        e.printStackTrace();
    }

    java.awt.EventQueue.invokeLater(() -> {
        new Principal().setVisible(true);
    });
    }

    
    

    public JButton getjButtonBuscar() {
        return jButtonBuscar;
    }

    public JButton getjButtonBuscarTrabajador() {
        return jButtonBuscarTrabajador;
    }

    public JButton getjButtonNuevaPropuesta() {
        return jButtonNuevaPropuesta;
    }

    public JButton getjButtonNuevoCliente() {
        return jButtonNuevoCliente;
    }

    public JButton getjButtonNuevoContrato() {
        return jButtonNuevoContrato;
    }

    public JButton getjButtonNuevoProyecto() {
        return jButtonNuevoProyecto;
    }

    public JButton getjButtonNuevoTrabajador() {
        return jButtonNuevoTrabajador;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonBuscarTrabajador;
    private javax.swing.JButton jButtonNuevaPropuesta;
    private javax.swing.JButton jButtonNuevoCliente;
    private javax.swing.JButton jButtonNuevoContrato;
    private javax.swing.JButton jButtonNuevoProyecto;
    private javax.swing.JButton jButtonNuevoTrabajador;
    private javax.swing.JLabel jLabelGeonorte;
    private javax.swing.JLabel jLabelicono;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
